version: '3.8'

services:
  web:
    build: .
    command: gunicorn quiz_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
